---
title: "Day 10 Partner Practice"
author: "Heather and Anna"
format: html
editor: visual
execute: 
  warning: false
  echo: false
---

## Partner 1: Task 1

```{r}
library(lterdatasampler)
library(tidyverse)
library(kableExtra)
```

```{r}
#View(pie_crab)
```

## Partner 2: Task 1

```{r}
#| fig-cap: "Crab data"
ggplot(data = pie_crab, aes(y = size, x = latitude)) +
  geom_point() +
  theme_minimal()+
  labs(caption = "Johnson, D. 2019. 
       Fiddler crab body size in salt marshes from Florida to Massachusetts, 
       USA at PIE and VCR LTER and NOAA NERR sites during summer 2016.
       ver 1. Environmental Data Initiative. 
       https://doi.org/10.6073/pasta/4c27d2e778d3325d3830a5142e3839bb 
       (Accessed 2023-08-25).")
```

```{r}
summary_table <- pie_crab %>% 
  group_by(site) %>% 
  summarize(mean_size = (round(mean(size, na.rm = TRUE), 2)),
            sd_size = (round(sd(size,na.rm = TRUE) ,2)),
            sample_size = n()
  ) |> 
  kable(col.names = c("Site", "Mean Carapace Width (mm)", "Standard Deviation of Carapace Width (mm)", "Sample Size")) |> 
  kable_styling(full_width = FALSE)

summary_table
```
